### PR TITLE
Updating Readme to point to PaperSpigot

### PR DESCRIPTION
**Pull request by ataranlen**
Added a link to paper's project in the ReadMe so the build instructions are up to date.

### CODE REVIEW

**Comment by HeroCC** [comment]
I saw your post on /r/admincraft. Do you have any idea how to build it without an IDE? I want to script the process if possible. Thanks!

**Comment by ataranlen** [comment]
Yeah, I built from the command line on one of my linux servers.

The final build step can be completed with a 'mvn clean install' instead of in the IDE.

**Comment by ataranlen** [comment]
1. git clone https://github.com/softpak/HOSE
2. git clone https://github.com/PaperMC/Paper
3. cp HOSE/pom.xml Paper/pom.xml
4. cd Paper/Paper-Server/src
5. patch -p1 < ../../../HOSE/src.patch
6. mvn clean install

These were my exact steps to build HOSE.

**Comment by ataranlen** [comment]
As the project is no longer based on paper, I'm just going to close this.

**Comment by softpak** [comment]
I am sorry but paper is not suitable for this project. Paper has many issues more then i thought in multi threading. So i just have to go back to spigot.

**Pull request closed without merging**
